const $=s=>document.querySelector(s), esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const db={get(k,d){try{return JSON.parse(localStorage.getItem("nd5."+k))??d}catch{return d}},set(k,v){localStorage.setItem("nd5."+k,JSON.stringify(v))}};
let route="home", challenge=0, question=0;
function go(r){route=r;render();scrollTo(0,0)} window.go=go;
const card=(x,c="")=>`<section class="card ${c}">${x}</section>`;
function days(){let d=db.get("reunion","");if(!d)return"—";return Math.ceil((new Date(d+"T12:00:00")-new Date())/864e5)}
function home(){return `<h1>Bonsoir vous deux ❤️</h1>${card(`<div class=muted>Prochaines retrouvailles</div><div class="big accent">J${days()>=0?"-":"+"}${Math.abs(days())}</div><input id=reunion type=date value="${esc(db.get("reunion",""))}"><button class=btn onclick="saveReunion()">Modifier la date</button>`,"hero")}<div class=grid>${[
["💌","Messages","messages"],["🔐","Espaces privés","private"],["✨","100 défis","challenges"],["💭","100 questions","questions"],["📅","Dates importantes","calendar"],["🔄","Sync chiffrée","sync"]].map(x=>card(`<div style="font-size:27px">${x[0]}</div><h2>${x[1]}</h2>`+`<button class="btn secondary" onclick="go('${x[2]}')">Ouvrir</button>`,"tile")).join("")}</div>`}
function saveReunion(){db.set("reunion",$("#reunion").value);render()}
function messages(){let a=db.get("messages",[]);return `<h1>💌 Nos messages</h1>${card(`<textarea id=msg placeholder="Écris quelque chose à ton amour…"></textarea><button class=btn onclick=addMsg()>Ajouter</button>`)}${a.slice().reverse().map(m=>card(`<div class=answer>${esc(m.text)}</div><div class=muted>${new Date(m.at).toLocaleString()}</div>`)).join("")}`}
function addMsg(){let t=$("#msg").value.trim();if(!t)return;let a=db.get("messages",[]);a.push({id:crypto.randomUUID(),text:t,at:Date.now()});db.set("messages",a);render()}
function qa(type){let arr=ND_DATA[type], idx=type==="challenges"?challenge:question, key=type+"Answers", ans=db.get(key,{});return `<h1>${type==="challenges"?"✨ Défis":"💭 Questions"}</h1><div class=muted>${Object.keys(ans).length}/100 réponses enregistrées</div>${card(`<div class=chip>${idx+1}/100</div><h2>${esc(arr[idx])}</h2><textarea id=qa>${esc(ans[idx]||"")}</textarea><button class=btn onclick="saveQA('${type}',${idx})">Enregistrer</button><button class="btn secondary" onclick="randomQA('${type}')">Au hasard</button>`)} `}
function saveQA(t,i){let a=db.get(t+"Answers",{});a[i]=$("#qa").value;db.set(t+"Answers",a);render()}
function randomQA(t){let n=Math.floor(Math.random()*100);if(t==="challenges")challenge=n;else question=n;render()}
function privateView(){let notes=db.get("privateNotes",{});return `<h1>🔐 Nos espaces privés</h1><p class=muted>25 rubriques, enregistrées uniquement sur cet appareil jusqu’à synchronisation.</p>${Object.entries(ND_DATA.spaces).map(([s,subs])=>card(`<h2>${esc(s)}</h2>`+subs.map(x=>`<label>${esc(x)}<textarea data-p="${esc(s+"|"+x)}">${esc(notes[s+"|"+x]||"")}</textarea></label>`).join("")+`<button class=btn onclick=savePrivate()>Enregistrer cet espace</button>`)).join("")}`}
function savePrivate(){let n=db.get("privateNotes",{});document.querySelectorAll("[data-p]").forEach(x=>n[x.dataset.p]=x.value);db.set("privateNotes",n);alert("Enregistré ❤️")}
function calendar(){let ev=db.get("events",[]).sort((a,b)=>a.date.localeCompare(b.date));return `<h1>📅 Calendrier</h1>${card(`<input id=et placeholder="Titre"><input id=ed type=date><textarea id=en placeholder="Note facultative"></textarea><button class=btn onclick=addEvent()>Ajouter la date</button>`)}${ev.map(e=>card(`<div class=event><b>${esc(e.date)} — ${esc(e.title)}</b><div class=muted>${esc(e.note)}</div><button class="btn danger" onclick="delEvent('${e.id}')">Supprimer</button></div>`)).join("")}`}
function addEvent(){if(!$("#et").value||!$("#ed").value)return;let a=db.get("events",[]);a.push({id:crypto.randomUUID(),title:$("#et").value,date:$("#ed").value,note:$("#en").value});db.set("events",a);render()}
function delEvent(id){db.set("events",db.get("events",[]).filter(x=>x.id!==id));render()}
function b64(b){return btoa(String.fromCharCode(...new Uint8Array(b)))}
function unb64(s){let x=atob(s),a=new Uint8Array(x.length);for(let i=0;i<x.length;i++)a[i]=x.charCodeAt(i);return a}
async function fp(key){let h=await crypto.subtle.digest("SHA-256",key);return [...new Uint8Array(h)].slice(0,12).map(x=>x.toString(16).padStart(2,"0")).join("").toUpperCase().match(/.{1,4}/g).join(" · ")}
function getKey(){let s=localStorage.getItem("nd5.coupleKey");return s?unb64(s):null}
async function makeKey(){let k=crypto.getRandomValues(new Uint8Array(32));localStorage.setItem("nd5.coupleKey",b64(k));render()}
async function importKey(){try{let k=unb64($("#keyin").value.trim());if(k.length!==32)throw 0;localStorage.setItem("nd5.coupleKey",b64(k));render()}catch{alert("Clé invalide")}}
async function pair(){let k=getKey();if(!k)return `<h1>🔐 Appairage</h1>${card(`<p class=muted>Aucune clé de couple sur cet appareil.</p><button class=btn onclick=makeKey()>Créer la clé du couple</button><h2>Ou rejoindre</h2><textarea id=keyin placeholder="Colle la clé reçue"></textarea><button class=btn onclick=importKey()>Importer</button>`)}`;let f=await fp(k), ks=b64(k);return `<h1>🔐 Appairage</h1>${card(`<h2>Empreinte</h2><div class=fp>${f}</div><p class=muted>Comparez cette empreinte sur les deux téléphones.</p>`)}${card(`<h2>Ajouter l’autre téléphone</h2><p class=muted>La clé ci-dessous donne accès aux données synchronisées. Transmets-la une seule fois à ta partenaire par un canal de confiance.</p><textarea id=keyout readonly>${ks}</textarea><button class=btn onclick=shareKey()>Partager la clé</button>`)}`}
async function shareKey(){let t=$("#keyout").value;if(navigator.share)await navigator.share({title:"Nous Deux — appairage",text:t});else{await navigator.clipboard.writeText(t);alert("Clé copiée")}}
function payload(){return {v:5,at:Date.now(),messages:db.get("messages",[]),challengesAnswers:db.get("challengesAnswers",{}),questionsAnswers:db.get("questionsAnswers",{}),privateNotes:db.get("privateNotes",{}),events:db.get("events",[]),reunion:db.get("reunion","")}}
async function encrypt(){let raw=getKey();if(!raw)return alert("Appaire d’abord les téléphones.");let iv=crypto.getRandomValues(new Uint8Array(12));let key=await crypto.subtle.importKey("raw",raw,"AES-GCM",false,["encrypt"]);let clear=new TextEncoder().encode(JSON.stringify(payload()));let ct=await crypto.subtle.encrypt({name:"AES-GCM",iv},key,clear);let out="NOUS-DEUX-ND5."+b64(iv)+"."+b64(ct);$("#packet").value=out;if(navigator.share)await navigator.share({title:"Nous Deux — Sync ND5",text:out})}
async function decrypt(){try{let raw=getKey(),p=$("#packet").value.trim().split(".");if(!raw||p.length!==3||p[0]!=="NOUS-DEUX-ND5")throw 0;let key=await crypto.subtle.importKey("raw",raw,"AES-GCM",false,["decrypt"]);let clear=await crypto.subtle.decrypt({name:"AES-GCM",iv:unb64(p[1])},key,unb64(p[2]));let x=JSON.parse(new TextDecoder().decode(clear));merge(x);alert("Paquet authentifié, déchiffré et fusionné ❤️")}catch{alert("Paquet refusé : clé incorrecte ou données modifiées.")}}
function merge(x){let uniq=(a,b)=>[...new Map([...a,...b].map(v=>[v.id||JSON.stringify(v),v])).values()];db.set("messages",uniq(db.get("messages",[]),x.messages||[]));db.set("events",uniq(db.get("events",[]),x.events||[]));db.set("challengesAnswers",{...db.get("challengesAnswers",{}),...(x.challengesAnswers||{})});db.set("questionsAnswers",{...db.get("questionsAnswers",{}),...(x.questionsAnswers||{})});db.set("privateNotes",{...db.get("privateNotes",{}),...(x.privateNotes||{})});if(x.reunion)db.set("reunion",x.reunion);render()}
function sync(){return `<h1>🔄 Sync ND5</h1>${card(`<h2>WhatsApp ne transporte que le paquet chiffré</h2><p class=muted>Chiffrement authentifié AES-256-GCM dans ton navigateur. Un paquet modifié ou provenant d’une autre clé est refusé.</p><button class=btn onclick=encrypt()>Chiffrer et partager</button>`)}${card(`<textarea id=packet placeholder="Colle ici NOUS-DEUX-ND5…"></textarea><button class=btn onclick=decrypt()>Vérifier, déchiffrer et fusionner</button>`)}`}
async function render(){let app=$("#app");let r=route==="home"?home():route==="messages"?messages():route==="challenges"?qa("challenges"):route==="questions"?qa("questions"):route==="private"?privateView():route==="calendar"?calendar():route==="sync"?sync():await pair();app.innerHTML=r}
if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js");render();
